### ISSUE TITLE
Investigate how best to expose errors to DAOs

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/polytone#11]
If a DAO executes a message via polytone, we should provide the same proposal close-on-execution-failure option as we do for normal messages. We should also make this error event visible to the DAO DAO indexer via queries.

**Comment by 0xekez** [comment]
there is leeway in how we design this. i don't think we are married to returning an unlabeled binary blob. developer UX is most important here.

also, two notes from conversation with larry and ethan

1. the error string is not stored in the merkle  tree, so the error fields in our callbacks will be the classic "codespace wasm: 5".
2. the attributes of the CosmWasm reply only contain attributes from x/wasm as they had to remove the rest due the SDK being non-deterministic.

**Comment by Art3miX** [comment]
We should return what we can and need, this ensures that if updates are made to the returned data, we pretty much get it for "free" (closest to free we can get them).
I think #19 is doing it right, its feels like you get a direct response from your sent msgs.

**Comment by 0xekez** [comment]
closing for #19
