### ISSUE TITLE
Add controller option to note

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/polytone#20]
The note contract should allow registering a "controller". This address may execute messages on behalf of other accounts, and only this address may execute messages. This makes it possible to build outposts, as a controller can list a NFT on behalf of a user after it has received a callback indicating that the NFT has been transferred successfully.

**Comment by 0xekez** [comment]
Before starting this, I recommend reading this wiki page which discusses how the controller will be used: https://github.com/DA0-DA0/polytone/wiki/How-Polytone-Supports-Outposts

Stargaze outposts is discussed there, but the controller is extremely powerful and we'll use it for the Covenant system as well.

**Comment by 0xekez** [comment]
@Art3miX - my spec here is really shitty, so as always, would love to hear your design thoughts and feel free to deviate from what i've written here.

**Comment by Art3miX** [comment]
a very strong argument in favor of `note-controlled` separate contract is that by having it in 2 different contracts, we can have an additional confirmation on instantiation.

Right now, if an outpost instantiate a note without a controller, there are no errors and everything will work fine, and the only way of knowing that its not working correctly is by doing the `getController` query, or by trying to execute a msg not from the controller (which will pass when it shouldn't).

While having a dedicated `note-controlled` contract, on instantiation we can confirm and verify the note is controlled by sender (or passed argument).

**Comment by 0xekez** [comment]
> While having a dedicated note-controlled contract, on instantiation we can confirm and verify the note is controlled by sender

this is a great point. if I have time this weekend i'll try and get the refactor done for that!

**Comment by 0xekez** [comment]
https://github.com/DA0-DA0/polytone/commit/4f41acbf8ffe2d9d6f2747abf20dbcf557ff8998
