### ISSUE TITLE
Contract specific libraries requirement

### ISSUE THREAD

**Issue by Art3miX** [DA0-DA0/polytone#38]
`Error during static Wasm validation: Wasm contract requires unavailable capabilities: {"cosmwasm_1_2"}`

I was trying to upload note on junod.

The issue:
Because we use the workspace dependency tree, all of our contracts will require the same dependencies, which is false, because for this specific example.
Note doesn't require cw v1.2 (instantiate2), but voice does.

The solution:
We either:
1. fully ignore workspace dependencies, and go per contract
2. go case by case and modify the specific issues we encounter.

I think 2 is better, because that way we will be able to control specific cases where changes are made instead of manually modifying all of the dependencies.

**Comment by 0xekez** [comment]
fixed! https://github.com/DA0-DA0/polytone/pull/42
