### ISSUE TITLE
need to test: controlled note can't execute on behalf of random address

### ISSUE THREAD

**Issue by Art3miX** [DA0-DA0/polytone#39]
I think we already have a test that makes sure Note 1 and Note 2 (both on the same ChainA) resolves in a different account addresses on ChainB.

But we need to make sure we have this covered, or else it might be possible to create a malicious controlled note on ChainA, and execute messages on behalf of any random address.

**Comment by 0xekez** [comment]
just merged the PR to remove the controller, so this isn't needed anymore
