### ISSUE TITLE
Move all ExecuteMsg / QueryMsg to package 

### ISSUE THREAD

**Issue by 0xphilipp** [DA0-DA0/polytone#47]
Importing a package is much easier, as otherwise the compiler has an issue referencing duplicated entries when using the contract as import:

error: duplicate symbol: instantiate
          >>> defined in /code/target/wasm32-unknown-unknown/release/deps/eris_oracle.eris_oracle.e76249d7-cgu.5.rcgu.o
          >>> defined in /code/target/wasm32-unknown-unknown/release/deps/libpolytone_note-3d72b2d641e73ad0.rlib(polytone_note-3d72b2d641e73ad0.polytone_note.e333f7ea-cgu.15.rcgu.o)

**Comment by Art3miX** [comment]
Why can't you use the library feature? (`features = ["library"]`)

**Comment by JakeHartnell** [comment]
> Why can't you use the library feature? (`features = ["library"]`)

Yeah, this is the way. @0xphilipp, try that and it should solve your issue.
